version: "3.3"

services:
  nginx:
    image: nginx:latest
    ports:
      - 9001:80
    depends_on:
      - go-master
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media

  db:
    image: postgres:15
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
     - "5432:5432"
    
  go-master:
    # image: go-master:latest
    build: .
    expose:
     - 9001
    env_file:
     - ./.env
    depends_on:
     - db

  go-worker:
    image: hosein3333/go-worker
    ports:
    - "8001:8001"
    depends_on:
      - db
      - go-master
    

volumes:
  static_volume:
  media_volume:
  postgres_data:
